version: '2'

services:
  app:
    build: .
    image: mkulumadzi/simple-sinatra
    links:
      - mongodb:mongodb
    ports:
      - "80:3000"
    environment:
      MONGO_URL: mongodb
  mongodb:
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
