server:
  image: mkulumadzi/ideas-node-server
  links:
    - mongodb:mongodb
  ports:
    - "8080:8080"
  environment:
    MONGO_HOST: mongodb
mongodb:
  image: mongo
  expose:
    - "27017"
  ports:
    - "27017:27017"
webapp:
  image: mkulumadzi/ideas-angular-client
  links:
  - server:api1
  ports:
  - "80:80"
